#pragma once

#include <string>
#include <vector>
#include <map>
#include <optional>
#include <fstream>
#include <sstream>

#include <QString>
#include <QMainWindow>
#include <QPushButton>
#include <QLineEdit>
#include <QVBoxLayout>
#include <QDialog>
#include <QDoubleSpinBox>
#include <QMessageBox>
#include <QTableWidget>
#include <QHeaderView>
#include <QMenuBar>
#include <QFileDialog>
#include <QStandardPaths>
#include <QCoreApplication>
#include <QFileInfo>
#include <QCloseEvent>
#include <QApplication>
#include <QLabel>
#include <QLayoutItem>
#include <QTextEdit>
#include <QScrollArea>